// Mock data for dashboard
export function getMockDashboardData() {
  return {
    totalMembers: 256,
    newMembersThisMonth: 12,
    pendingUpdateRequests: 8,
    updateRequestsThisWeek: 5,
    totalCampRegistrations: 178,
    registrationsThisWeek: 24,
    branches: ["La", "Budumburam", "Domeabra", "UK"],
    countries: ["Ghana", "UK"],
    membershipGrowth: [
      { name: "Jan", total: 18 },
      { name: "Feb", total: 22 },
      { name: "Mar", total: 15 },
      { name: "Apr", total: 25 },
      { name: "May", total: 30 },
      { name: "Jun", total: 12 },
    ],
    recentActivities: [
      {
        id: "1",
        type: "new_member",
        title: "New Member Registered",
        description: "John Doe joined the church",
        timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(), // 30 minutes ago
      },
      {
        id: "2",
        type: "update_request",
        title: "Information Update Request",
        description: "Jane Smith requested an update to her contact information",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), // 2 hours ago
      },
      {
        id: "3",
        type: "camp_registration",
        title: "Camp Registration",
        description: "Michael Johnson registered for the upcoming camp",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(), // 5 hours ago
      },
      {
        id: "4",
        type: "new_member",
        title: "New Member Registered",
        description: "Sarah Williams joined the church",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(), // 8 hours ago
      },
      {
        id: "5",
        type: "update_request",
        title: "Information Update Request",
        description: "Robert Brown requested an update to his address",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), // 1 day ago
      },
    ],
  }
}

// Mock data for members
export function getMockMembers() {
  return [
    {
      id: "1",
      full_name: "John Doe",
      gender: "Male",
      dob: "1980-01-15",
      email: "john.doe@example.com",
      digital_address: "GA-123-4567",
      location: "Accra, Ghana",
      marital_status: "Married",
      phone_number: "1234567890",
      whatsapp_number: "1234567890",
      occupation_status: "Employed",
      organization: "Tech Company Ltd",
      branch: "La",
      created_at: "2023-01-01T00:00:00Z",
      updated_at: "2023-01-01T00:00:00Z",
    },
    {
      id: "2",
      full_name: "Jane Smith",
      gender: "Female",
      dob: "1985-05-20",
      email: "jane.smith@example.com",
      digital_address: "GA-987-6543",
      location: "Tema, Ghana",
      marital_status: "Single",
      phone_number: "9876543210",
      whatsapp_number: "9876543210",
      occupation_status: "Student",
      organization: "University of Ghana",
      branch: "Budumburam",
      created_at: "2023-01-02T00:00:00Z",
      updated_at: "2023-01-02T00:00:00Z",
    },
    {
      id: "3",
      full_name: "Michael Johnson",
      gender: "Male",
      dob: "1975-08-10",
      email: "michael.johnson@example.com",
      digital_address: "GA-456-7890",
      location: "Accra, Ghana",
      marital_status: "Married",
      phone_number: "5556667777",
      whatsapp_number: "5556667777",
      occupation_status: "Employed",
      organization: "Bank of Ghana",
      branch: "La",
      created_at: "2023-02-15T00:00:00Z",
      updated_at: "2023-02-15T00:00:00Z",
    },
    {
      id: "4",
      full_name: "Sarah Williams",
      gender: "Female",
      dob: "1990-03-25",
      email: "sarah.williams@example.com",
      digital_address: "UK-789-0123",
      location: "London, UK",
      marital_status: "Single",
      phone_number: "4445556666",
      whatsapp_number: "4445556666",
      occupation_status: "Employed",
      organization: "NHS",
      branch: "UK",
      created_at: "2023-03-10T00:00:00Z",
      updated_at: "2023-03-10T00:00:00Z",
    },
    {
      id: "5",
      full_name: "Robert Brown",
      gender: "Male",
      dob: "1982-11-05",
      email: "robert.brown@example.com",
      digital_address: "GA-321-6547",
      location: "Kumasi, Ghana",
      marital_status: "Divorced",
      phone_number: "7778889999",
      whatsapp_number: "7778889999",
      occupation_status: "Self-employed",
      organization: "Brown Enterprises",
      branch: "Domeabra",
      created_at: "2023-04-20T00:00:00Z",
      updated_at: "2023-04-20T00:00:00Z",
    },
  ]
}

// Mock data for update requests
export function getMockUpdateRequests() {
  return [
    {
      id: "1",
      user_id: "2",
      full_name: "Jane Smith",
      gender: "Female",
      dob: "1985-05-20",
      email: "jane.smith@example.com",
      digital_address: "GA-987-6543",
      location: "Accra, Ghana", // Changed from Tema to Accra
      marital_status: "Married", // Changed from Single to Married
      phone_number: "9876543210",
      whatsapp_number: "9876543210",
      occupation_status: "Employed", // Changed from Student to Employed
      organization: "Ghana Education Service", // Changed from University of Ghana
      branch: "Budumburam",
      reason: "I've recently moved to Accra and got married. Also started working at GES.",
      status: "pending",
      created_at: "2023-06-15T00:00:00Z",
    },
    {
      id: "2",
      user_id: "5",
      full_name: "Robert Brown",
      gender: "Male",
      dob: "1982-11-05",
      email: "robert.brown@example.com",
      digital_address: "UK-654-3210", // Changed to UK address
      location: "Manchester, UK", // Changed from Kumasi, Ghana
      marital_status: "Divorced",
      phone_number: "7778889999",
      whatsapp_number: "7778889999",
      occupation_status: "Employed", // Changed from Self-employed
      organization: "Manchester University", // Changed from Brown Enterprises
      branch: "UK", // Changed from Domeabra
      reason: "I've relocated to the UK for work and would like to update my branch and address details.",
      status: "approved",
      created_at: "2023-06-10T00:00:00Z",
    },
    {
      id: "3",
      user_id: "1",
      full_name: "John Doe",
      gender: "Male",
      dob: "1980-01-15",
      email: "john.doe@newemail.com", // Changed email
      digital_address: "GA-123-4567",
      location: "Accra, Ghana",
      marital_status: "Married",
      phone_number: "1234567890",
      whatsapp_number: "9998887777", // Changed WhatsApp number
      occupation_status: "Employed",
      organization: "Tech Company Ltd",
      branch: "La",
      reason: "I've changed my email address and WhatsApp number.",
      status: "rejected",
      created_at: "2023-06-05T00:00:00Z",
    },
    {
      id: "4",
      user_id: "3",
      full_name: "Michael Johnson",
      gender: "Male",
      dob: "1975-08-10",
      email: "michael.johnson@example.com",
      digital_address: "GA-456-7890",
      location: "Accra, Ghana",
      marital_status: "Divorced", // Changed from Married to Divorced
      phone_number: "5556667777",
      whatsapp_number: "5556667777",
      occupation_status: "Employed",
      organization: "Bank of Ghana",
      branch: "La",
      reason: "I need to update my marital status as I recently got divorced.",
      status: "pending",
      created_at: "2023-06-18T00:00:00Z",
    },
    {
      id: "5",
      user_id: "4",
      full_name: "Sarah Williams",
      gender: "Female",
      dob: "1990-03-25",
      email: "sarah.williams@example.com",
      digital_address: "UK-789-0123",
      location: "London, UK",
      marital_status: "Married", // Changed from Single to Married
      phone_number: "4445556666",
      whatsapp_number: "4445556666",
      occupation_status: "Employed",
      organization: "NHS",
      branch: "UK",
      reason: "I got married last month and would like to update my marital status.",
      status: "pending",
      created_at: "2023-06-20T00:00:00Z",
    },
  ]
}

// Mock data for camp registrations
export function getMockCampRegistrations() {
  return [
    {
      id: "1",
      full_name: "John Doe",
      email: "john.doe@example.com",
      phone_number: "1234567890",
      gender: "Male",
      attendee_type: "MEMBER",
      branch: "La",
      attendance_date: "August 14, 2024",
      emergency_contact_name: "Jane Doe",
      emergency_contact_number: "9876543210",
      created_at: "2023-06-01T00:00:00Z",
      checked_in: true,
    },
    {
      id: "2",
      full_name: "Jane Smith",
      email: "jane.smith@example.com",
      phone_number: "9876543210",
      gender: "Female",
      attendee_type: "MEMBER",
      branch: "Budumburam",
      attendance_date: "August 15, 2024",
      emergency_contact_name: "John Smith",
      emergency_contact_number: "1234567890",
      created_at: "2023-06-02T00:00:00Z",
      checked_in: false,
    },
    {
      id: "3",
      full_name: "Michael Johnson",
      email: "michael.johnson@example.com",
      phone_number: "5556667777",
      gender: "Male",
      attendee_type: "MEMBER",
      branch: "La",
      attendance_date: "August 16, 2024",
      emergency_contact_name: "Sarah Johnson",
      emergency_contact_number: "7778889999",
      created_at: "2023-06-03T00:00:00Z",
      checked_in: false,
    },
    {
      id: "4",
      full_name: "Sarah Williams",
      email: "sarah.williams@example.com",
      phone_number: "4445556666",
      gender: "Female",
      attendee_type: "MEMBER",
      branch: "UK",
      attendance_date: "August 14, 2024",
      emergency_contact_name: "Robert Williams",
      emergency_contact_number: "6667778888",
      created_at: "2023-06-04T00:00:00Z",
      checked_in: true,
    },
    {
      id: "5",
      full_name: "Robert Brown",
      email: "robert.brown@example.com",
      phone_number: "7778889999",
      gender: "Male",
      attendee_type: "MEMBER",
      branch: "Domeabra",
      attendance_date: "August 15, 2024",
      emergency_contact_name: "Mary Brown",
      emergency_contact_number: "8889990000",
      created_at: "2023-06-05T00:00:00Z",
      checked_in: false,
    },
    {
      id: "6",
      full_name: "Emily Davis",
      email: "emily.davis@example.com",
      phone_number: "1112223333",
      gender: "Female",
      attendee_type: "VISITOR",
      branch: "La",
      attendance_date: "August 16, 2024",
      emergency_contact_name: "David Davis",
      emergency_contact_number: "3334445555",
      created_at: "2023-06-06T00:00:00Z",
      checked_in: false,
    },
    {
      id: "7",
      full_name: "Daniel Wilson",
      email: "daniel.wilson@example.com",
      phone_number: "2223334444",
      gender: "Male",
      attendee_type: "VISITOR",
      branch: "Budumburam",
      attendance_date: "August 14, 2024",
      emergency_contact_name: "Emma Wilson",
      emergency_contact_number: "4445556666",
      created_at: "2023-06-07T00:00:00Z",
      checked_in: true,
    },
  ]
}

